// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu1OvJ-RskKas1fgmHA_GSn-9DWpNmZwU',
    appId: '1:82487684572:web:665246a403e6d523a4b319',
    messagingSenderId: '82487684572',
    projectId: 'notificationwebpreecha',
    authDomain: 'notificationwebpreecha.firebaseapp.com',
    storageBucket: 'notificationwebpreecha.appspot.com',
    measurementId: 'G-EEM82MHNG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpC9Q8bUT0TTlLXf0metRfpZxxgiJQDso',
    appId: '1:82487684572:android:1bc450f8330aceb8a4b319',
    messagingSenderId: '82487684572',
    projectId: 'notificationwebpreecha',
    storageBucket: 'notificationwebpreecha.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT_L1Vn4aILKib08TRnnRUTxrBUIJx6cg',
    appId: '1:82487684572:ios:f361f710aaa75efda4b319',
    messagingSenderId: '82487684572',
    projectId: 'notificationwebpreecha',
    storageBucket: 'notificationwebpreecha.appspot.com',
    iosBundleId: 'com.example.notificationWeb',
  );
}
